"""empty message

Revision ID: 365c6ad8772d
Revises: 89442b8edcb9
Create Date: 2022-04-07 10:27:59.171905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365c6ad8772d'
down_revision = '89442b8edcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('picture', 'pic',
               existing_type=sa.BLOB(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('picture', 'pic',
               existing_type=sa.BLOB(),
               nullable=False)
    # ### end Alembic commands ###
