"""empty message

Revision ID: 89442b8edcb9
Revises: 5e0c0556e32a
Create Date: 2022-04-07 10:27:02.234554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89442b8edcb9'
down_revision = '5e0c0556e32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('pic_name', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'pic_name')
    # ### end Alembic commands ###
